version: '3'
services:

  ### Nginx container #########################################

  nginx:
      image: nginx:alpine
      container_name: nginx
      ports:
        - "${HTTP_PORT}:80"
        - "${HTTPS_PORT}:443"
      volumes:
        - ${PROJECT_FOLDER}:/etc/nginx/html/:rw
        - ./data/formality/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./data/formality/nginx/config/conf.d:/etc/nginx/conf.d:ro
        - ./data/formality/nginx/log:/var/log/nginx:rw
      
      restart: always
      privileged: true
      networks:
        - net-php

  ### PHP container #########################################

  php:
      build:
        context: ./build/php
        args:
          TIME_ZONE: ${GLOBAL_TIME_ZONE}
          CHANGE_SOURCE: ${GLOBAL_CHANGE_SOURCE}
      volumes:
        - ${PROJECT_FOLDER}:/etc/nginx/html:rw
        - ./data/formality/php/config/php.ini:/usr/local/etc/php/php.ini:ro
        - ./data/formality/php/config/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
        - ./data/formality/php/log:/var/log:rw
      restart: always
      privileged: true
      container_name: php
      networks:
        - net-php
        - net-mysql
        - net-redis
        - net-mongodb
        - net-memcached
        - net-rabbitmq

  ### Mysql container #########################################

  mysql:
      image: mysql:${MYSQL_VERSION}
      container_name: mysql
      ports:
        - "${MYSQL_PORT}:3306"
      volumes:
        - ./data/formality/mysql/data:/var/lib/mysql:rw
        - ./data/formality/mysql/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
        - ./data/formality/mysql/log:/var/log/mysql:rw
      restart: always
      privileged: true
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      networks:
        - net-mysql

  ### Redis container #########################################

  redis:
      image: redis:latest
      container_name: redis
      ports:
        - "${REDIS_PORT}:6379"
      volumes:
        - ./data/formality/redis/config/redis.conf:/usr/local/etc/redis/redis.conf:ro
        - ./data/formality/redis/log/redis.log:/var/log/redis/redis.log:rw
      restart: always
      privileged: true
      networks:
        - net-redis

  ### Mongodb container #########################################

  mongodb:
      image: mongo:${MONGODB_VERSION}
      container_name: mongodb
      environment:
          MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USERNAME}"
          MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"
      volumes:
        - ./data/formality/mongo:/data/db:rw
        - ./data/formality/mongo/mongo_key:/mongo:rw
      ports:
         - "${MONGODB_PORT}:27017"
      networks:
        - net-mongodb
      command:
         --auth

  ### Memcached container #########################################
  memcached:
      image: memcached:${MEMCACHED_VERSION}
      container_name: memcached
      ports:
        - "${MEMCACHED_PORT}:11211"
      environment:
         MEMCACHED_CACHE_SIZE: "${MEMCACHED_CACHE_SIZE}"
      networks:
        - net-memcached

  ### Rabbitmq container #########################################
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - ./data/formality/rabbitmq/data:/var/lib/rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - net-rabbitmq

networks:
  net-php:
  net-mysql:
  net-redis:
  net-mongodb:
  net-memcached:
  net-rabbitmq: